CryptVault.Web/Controllers/CardController.cs
using AutoMapper;
using CryptVault.Core.Interfaces;
using CryptVault.Core.Models.Card;
using CryptVault.Core.Models.Password;
using CryptVault.Core.Services;
using CryptVault.Web.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace CryptVault.Web.Controllers
{
	public class CardController : Controller
	{
		private readonly ICardService cardService;
        public readonly IMapper autoMapper;

        public CardController(ICardService _cardService, IMapper _autoMapper)
		{
			this.cardService = _cardService;
            autoMapper = _autoMapper;
		}


		[HttpGet]
		public async Task<IActionResult> MyCards()
		{
			List<CardViewModel> cards = await cardService.GetCardsByUserIdAsync(User.Id());
			return View(cards);
		}

		[HttpGet]
		public IActionResult AddCard() 
		{ 
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> AddCard(AddCardViewModel model)
		{
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                model.UserId = User.Id();
                await cardService.CreateAsync(model);
            }
            catch (Exception ms)
            {
                ModelState.AddModelError("", ms.Message);
            }

            return RedirectToAction(nameof(MyCards));
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            if (!(await cardService.ExistsById(id)))
            {
                ModelState.AddModelError("", "Card doesn't exist!");
                //return RedirectToAction(nameof(MyCards));
            }

            if (User.Id() != await cardService.GetUserId(id))
            {
                ModelState.AddModelError("", "Access denied! You cannot access another users cards!");
                //return RedirectToAction(nameof(MyCards));
            }

            var cardModel = autoMapper.Map<EditCardViewModel>(await cardService.GetCardById(id));
            return View(cardModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, EditCardViewModel model)
        {
            if (!(await cardService.ExistsById(id)))
            {
                ModelState.AddModelError("", "Card does not exist!");
                return View(model);
            }

            if (await cardService.GetUserId(id) != User.Id())
            {
                ModelState.AddModelError("", "Cannot edit another users cards");
                return View(model);
            }

            if (ModelState.IsValid == false)
            {
                return View(model);
            }

            await cardService.EditAsync(id, model);

            return RedirectToAction(nameof(MyCards));
        }
    }
}

CryptVault.Web/Controllers/PasswordController.cs
using AutoMapper;
using CryptVault.Core.Interfaces;
using CryptVault.Core.Models.Password;
using CryptVault.Data.Entities;
using CryptVault.Web.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CryptVault.Web.Controllers
{
    [Authorize]
    public class PasswordController : Controller
    {
        public readonly IPasswordService passwordService;
        public readonly UserManager<ApplicationUser> userManager;
        public readonly IMapper autoMapper;
        public PasswordController(IPasswordService _passwordService, UserManager<ApplicationUser> _userManager, IMapper autoMapper)
        {
            this.passwordService = _passwordService;
            this.userManager = _userManager;
            this.autoMapper = autoMapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> MyPasswords()
        {
            var passwords = await passwordService.GetPasswordsByUserIdAsync(User.Id());
            return View(passwords);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddPasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                model.UserId = User.Id();
                await passwordService.CreateAsync(model);
            }
            catch (Exception ms)
            {
                ModelState.AddModelError("", ms.Message);
            }

            return RedirectToAction(nameof(MyPasswords));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            if (!(await passwordService.ExistsById(id)))
            {
                ModelState.AddModelError("", "Password doesn't exist!");
                return RedirectToAction(nameof(MyPasswords));
            }

            if (User.Id() != await passwordService.GetUserId(id))
            {
                ModelState.AddModelError("", "Access denied! You cannot access another users password!");
                return RedirectToAction(nameof(MyPasswords));
            }
            
            var pwdModel = autoMapper.Map<EditPasswordViewModel>(await passwordService.GetPasswordById(id));
            return View(pwdModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, EditPasswordViewModel model)
        {
            if (!(await passwordService.ExistsById(id)))
            {
                ModelState.AddModelError("", "Password does not exist!");
                return View(model);
            }
            
            if (await passwordService.GetUserId(id) != User.Id())
            {
                ModelState.AddModelError("", "Cannot edit another users password");
                return View(model);
            }

            if (ModelState.IsValid == false)
            {
                return View(model);
            }

            await passwordService.EditAsync(id, model);

            return RedirectToAction(nameof(MyPasswords));
        }

    }
}

CryptVault.Web/Views/Shared/Layouts/_GuestHomePageLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>CryptVault</title>
    <link rel="icon" type="image/x-icon" href="~/assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Google fonts-->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,600;1,600&amp;display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,500;0,600;0,700;1,300;1,500;1,600;1,700&amp;display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,400;1,400&amp;display=swap" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/GuestHomeStyle.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CryptVault.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/theme.css" asp-append-version="true" />
</head>

<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-white fixed-top shadow-sm" id="mainNav">
        <div class="container px-5">
            <a class="navbar-brand fw-bold text-red" href="#page-top">CryptVault</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="bi-list"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
                    <li class="nav-item"><a class="nav-link me-lg-3 text-white" asp-area="Identity" asp-page="/Account/Login"><span class="text-red">Login</span></a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3 text-white" asp-area="Identity" asp-page="/Account/Register"><span class="text-red">Register</span></a></li>
                </ul>
            </div>
        </div>
    </nav>
    @RenderBody()
    <!-- Footer-->
    <footer class="bg-secondary text-center py-5">
        <div class="container px-5">
            <div class="text-white-50 small">
                <div class="mb-2">&copy; Your Website 2023. All Rights Reserved.</div>
                <a href="#!">Privacy</a>
                <span class="mx-1">&middot;</span>
                <a href="#!">Terms</a>
                <span class="mx-1">&middot;</span>
                <a href="#!">FAQ</a>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/site.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>

</html>

CryptVault.Web/Views/Shared/Layouts/_LandingPageLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

CryptVault.Web/Views/Shared/Layouts/_LayoutNavbarless.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CryptVault</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CryptVault.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/theme.css" asp-append-version="true" />
</head>
<body class="m-0">
    <div id="particles-js" class="position-fixed top-0 left-0 w-100 h-100"></div>
    <div class="container">
        <main role="main" class="pb-0">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/particleJS/particles.js" ></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/bgParticles.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CryptVault.Web/Views/Shared/Layouts/_PanelLayout.cshtml
@using CryptVault.Data.Entities;
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Identity;
@inject UserManager<ApplicationUser> userManager

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CryptVault</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CryptVault.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/theme.css" asp-append-version="true" />

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

</head>

<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Sidebar Start -->
        <div id="particles-js" class="position-fixed top-0 left-0 w-100 h-100"></div>
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a asp-action="Index" asp-controller="Home" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-user-edit me-2"></i>CryptVault</h3>
                </a>
                <div class="navbar-nav w-100">
                    <a asp-controller="Password" asp-action="MyPasswords" class="nav-item nav-link"><i class="far fa-file-alt me-2"></i>My Passwords</a>
                    <a asp-controller="Card" asp-action="MyCards" class="nav-item nav-link"><i class="fa fa-credit-card me-2"></i>My Cards</a>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->
        <!-- Content Start -->
        <div class="content bg-transparent">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a asp-controller="Home" asp-action="Index" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
                </a>
                <a class="sidebar-toggler flex-shrink-0" href="#">
                    <i class="fa fa-bars"></i>
                </a>
                <div class="navbar-nav align-items-center ms-auto">
                </div>
                <partial name="_LoginPartial" />
            </nav>
            <!-- Navbar End -->
            <!-- Sub nav -->
            @if (Url.RouteUrl(ViewContext.RouteData.Values)!.StartsWith("/Identity/Account/"))
            {
                <partial name="_SubNav"/>
            }
            <!-- Blank Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row vh-100 bg-secondary rounded justify-content-center mx-0 overflow-auto">
                    @RenderBody()
                </div>
            </div>
            <!-- Blank End -->
            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary rounded-top p-4">
                    <div class="row">
                        <div class="col col-sm text-center text-sm-start">
                            &copy; <a href="#">CryptVault</a>
                        </div>
                        <div class="col col-sm text-center text-sm-center">
                            <span class="text-center" id="clock">@DateTime.Now.ToString("hh:mm:ss")</span>
                        </div>
                        <div class="col col-sm text-center text-sm-end">
                            <a href="https://github.com/SchoolTeamProjectApp/CryptVault">Github<i class="bi bi-github mx-1"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/lib/particleJS/particles.js"></script>
    <script src="~/js/bgParticles.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>